### PR TITLE
Adds isinf

### PR DESCRIPTION
**Pull request by matthewfernst**
## Proposed changes

Please include a description of the problem or feature this PR is addressing. If there is a corresponding issue, include the issue #.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Review by awni — CHANGES_REQUESTED** [review]
Could you please check my comments in #449 and apply them here? Most of them are relevant.

**Comment by matthewfernst** [comment]
> Could you please check my comments in #449 and apply them here? Most of them are relevant.

Hi @awni, thank you for taking a look! So sorry, I'm still getting used to mlx and was hoping for some direction. I updated the `isinf` call to the below. My ops test for the C++ side work but my python tests all fail with `infs` being `False` always. I was curious if you had any ideas? I thought maybe it was a pybind issue, but it seems correct? Thank you for your help!

```c++
array isinf(const array& a, StreamOrDevice s /* = {} */) {
  return equal(a, array(std::numeric_limits<float>::infinity(), a.dtype()), s);
}
```

**Review by awni — APPROVED** [review]
I'm not sure why your python tests don't work. They worked fine for me 🤔 .

I pushed a few changes, you can take a look to see. 

Thanks for the contribution!!

**Comment by awni** [comment]
It's psosible there is something wrong with your environment.. not sure 🤔 .


You could check to make sure it's using the right mlx build `python -c "import mlx.core as mx; print(mx.__file__)"` should point to a file in you source distribution.

**Comment by awni** [comment]
No prob, I use conda

**Pull request merged**
