### PR TITLE
Don't use make_unique to create shared_ptr

### PR DESCRIPTION
**Pull request by zcbenz**
## Proposed changes

The code compiled because shared_ptr's constructor actually accepts unique_ptr.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Review by awni — APPROVED** [review]
Thanks! Will merge when tests clear.

**Review by awni — APPROVED** [review]
Thanks!!

**Review by awni — APPROVED** [review]

**Comment by awni** [comment]
Could you rebase it looks like there is a conflict?

**Comment by zcbenz** [comment]
Rebased.

**Pull request merged**
