### PR TITLE
Fix OOB read in qmv when non-divisible by blocksize

### PR DESCRIPTION
**Pull request by angeloskath**
As title suggests, it fixes out of bounds reads for `qmv` when the vector size is not divisible by 256 which is the block size for the small kernel. It adds ~4% in the micro-benchmark but I didn't really see any overhead in actual generation.

It also adds some code duplication which I hate but I think it is not too bad for now.

### CODE REVIEW

**Comment by awni** [comment]
Closes https://github.com/ml-explore/mlx-examples/issues/452

**Comment by awni** [comment]
Maybe worth adding a test for this / testing more unusual shapes since the dispatch is getting a bit complex? Or do you prefer to do that in some longer running CI thing?

**Review by awni — APPROVED** [review]
Thanks for the quick fix 🚀

**Comment by angeloskath** [comment]
Yeah definitely longer running CI / fuzzing. It had to do a loop of 20 with sizes 2k x 5k and some additions etc otherwise it would not show up and even then it was dependent on the rest of the program ie running that test alone would not fail.

**Pull request merged**
