### PR TITLE
Add `conda` install option to README.md

### PR DESCRIPTION
**Pull request by sugatoray**
Add conda install option in docs.

## Proposed changes

This PR updates the README file with the installation option for installing `mlx` with `conda` from conda-forge channel.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by awni** [comment]
I'm not sure we should advertise this in the README as it appears the conda forge distribution is lagging the pypi one. 

@xhochy and @ngam is the update waiting for review?

**Comment by sugatoray** [comment]
> (As an aside, @sugatoray is a great conda-forge contributor who once made a nifty web tool that made converting pip packages to conda packages a breeze 👍)

Thank you, for the shout out @ngam. Please feel free to add me to the list of maintainers in `mlx-feedstock`.

**Comment by awni** [comment]
Thank you all for the thoughtful responses! I'd really like to keep MLX updated on conda-forge. So we'll do our best not to break things for you again!

**Comment by awni** [comment]
If it makes sense to add me as a maintainer I am up for it. I don't know much about your system yet so I probably will not default to be the first reviewer but I'm happy to be in the loop.

**Review by awni — APPROVED** [review]
You've convinced me we should add this. We can revisit if maintenance lags or becomes an issue.

**Comment by sugatoray** [comment]
@awni Thank you for review/merging the PR.

**Pull request merged**
