### PR TITLE
Adding LSTMCell

### PR DESCRIPTION
**Pull request by Rifur13**
## Proposed changes

This PR adds LSTMCell. It represents a single cell of an LSTM layer, and processes one time step of the sequence data at a time.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by Rifur13** [comment]
I need this layer for a model I’m working and it would be nice to merge it here. I see the open PR to add LSTM, but it has a lot more functionality on top and won’t share code. 

Let me know what you think before I clean it up and start writing docs and tests.

**Comment by awni** [comment]
We don't intend to have the concept of "Cell" for recurrent nets in general. One should be able to use the LSTM in #268 for the same purpose.  In fact #268 originally had cells like that and we decided to remove them for simplicity.

If you aren't able to use #268 that would be useful to understand why

**Comment by Rifur13** [comment]
Ok I see thanks, let’s close this PR then.

In my case I can use a LSTM and just call it one time step at a time.

FWIW my reasons for adding this were:
- Better readability because I would expect LSTM to be applied for all time steps.
- The input to LSTM will have the shape (time_steps, input_size) or (batch, time_steps, input_size), so I would avoid reshaping from (batch, input_size) to (batch, 1, input_size)

**Comment by awni** [comment]
Makes sense, thanks for the explanation. The LSTM can indeed be used on a per-time-step basis. The reshaping is maybe not so nice, but I think that's something we could fix in that layer.

**Pull request closed without merging**
