### PR TITLE
Adds issue template with common questions

### PR DESCRIPTION
**Pull request by dc-dc-dc**
## Proposed changes

Adds an issue template for github with common questions and auto assigns `bug-unconfirmed` tag to the issue

## Checklist

Put an `x` in the boxes that apply.

- [ ] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [ ] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by SputNikPlop** [comment]
This seems great. What about leaving the issue without a label as to represent that it is waiting for triage by the team?

**Review by awni — COMMENTED** [review]
Nice! I would also remove the default label just because I think it might get used for things which are likely not actually bugs. O/w awesome, thanks for adding!

**Comment by dc-dc-dc** [comment]
Feel free to modify as you see fit btw, I just added some basic questions I saw repeated

**Review by awni — APPROVED** [review]
Thanks for adding this!!

**Pull request merged**
