### PR TITLE
Donation bug

### PR DESCRIPTION
**Pull request by awni**
- Fix bug with donation in softmax, rmsnorm+vjp, layernorm+vjp
- Fix a couple other bugs in softmax + vjps

### CODE REVIEW

**Review by angeloskath — APPROVED** [review]
Very nice!

My understanding is that we would copy and then not donate because `copies.back()` and `x_copy` were copies of the same array. Wouldn't returning `copies.back()` have the same result? Either way, great fix.

**Comment by awni** [comment]
> My understanding is that we would copy and then not donate because copies.back() and x_copy were copies of the same array. 

I think it's a little more subtle than that. Even in the no copy case we did not donate before (the use count became 2 after calling `check_input`).  I think C++ extends the lifetime of the `return x` since we hold a `const & ` reference to it. So the use count gets incremented and does not decrement until that reference is gone.

**Comment by angeloskath** [comment]
Interesting. What are the chances the return type is inferred to be `array` instead of `array&` or `cost array&`?

**Comment by awni** [comment]
Great point, this works and is nicer actually
```
  auto check_input = [&copies, &s](const array& x) -> const array& {
    bool no_copy = x.strides()[x.ndim() - 1] == 1;
    if (x.ndim() > 1) {
      auto s = x.strides()[x.ndim() - 2];
      no_copy &= (s == 0 || s == x.shape().back());
    }
    if (no_copy) {
      return x;
    } else {
      copies.push_back(array(x.shape(), x.dtype(), nullptr, {}));
      copy_gpu(x, copies.back(), CopyType::General, s);
      return copies.back();
    }
  };
```

**Pull request merged**
