### PR TITLE
covn3d mapping + operator implem

### PR DESCRIPTION
**Pull request by AndreSlavescu**
## Proposed changes

Please include a description of the problem or feature this PR is addressing. If there is a corresponding issue, include the issue #.

Work in progress implementation of Conv3d

## Checklist

- [x] python API operator implementation
- [x] python API module mapping implementation
- [x] C++ api operator implementation
- [x] C++ operator interface
- [ ] Naive Conv3D METAL kernel
- [ ] necessary tests
 
Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by dc-dc-dc** [comment]
Might want to check in with @jagrit06 as he is working on an update to conv #651

**Comment by awni** [comment]
What's the status of this PR? Should we move it forward or close it?

**Comment by AndreSlavescu** [comment]
> What's the status of this PR? Should we move it forward or close it?

I will continue on it in a couple of days. I was waiting initially for @jagrit06 PR to be merged. Now that it's merged I will work based on those changes to add the frontend implementations.

**Comment by awni** [comment]
@AndreSlavescu are you coming back to this or should we close?

**Comment by awni** [comment]
Closing as inactive.

**Pull request closed without merging**
