### PR TITLE
feat: added autoflake & docformatter to pre-commit

### PR DESCRIPTION
**Pull request by NripeshN**
## Proposed changes

dded docformatter to pre-commit

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by NripeshN** [comment]
Hey @awni 
Could you please review this PR

**Comment by awni** [comment]
Looks like the tests are falling. Could you check that?

I like the idea of the doc formatter, but also a lot of our docs are in C++ code...so it won't catch that 🤔 .

**Comment by NripeshN** [comment]
> Looks like the tests are falling. Could you check that?
> 
> I like the idea of the doc formatter, but also a lot of our docs are in C++ code...so it won't catch that 🤔 .

Yup, C++ does not have a single, universally adopted documentation standard like Python's PEP 257. We could build a custom formatter for mlx codebase though. Having a python docformatter for now would be great. I will take a look at why the tests are failing

**Comment by NripeshN** [comment]
@awni 
What do you think about this PR?

**Comment by awni** [comment]
I'm ok with adding these to the pre-commit hooks, they look generally useful and not too intrusive

CC @angeloskath or @jagrit06 may have some opinions.

I'll wait a little to hear from others then do a quick review. Also would be great if you could rebase this @NripeshN

**Comment by awni** [comment]
Closing as inactive.

**Pull request closed without merging**
