### PR TITLE
fix typo: gater -> gather

### PR DESCRIPTION
**Pull request by davidkoski**
## Proposed changes

fix typo: gater -> gather

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by davidkoski** [comment]
Test failure, but it seems to be unrelated to this change:

```
ERROR: test_array_pickle (test_array.TestArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/python/tests/test_array.py", line 848, in test_array_pickle
    pickle.dumps(x)
RuntimeError: nanobind::detail::ndarray_wrap(): could not convert ndarray to NumPy array: ValueError: Unable to avoid copy while creating an array as requested.
```

**Comment by barronalex** [comment]
Fixed the pickle test in #1221 so once that's in I'll rebase this and merge it.

**Comment by awni** [comment]
@davidkoski can you rebase on main. The tests should clear now.

**Comment by barronalex** [comment]
Tried to rebase but looks like I don't have permission on @davidkoski's branch

**Pull request merged**
