### PR TITLE
Add type hint for Module

### PR DESCRIPTION
**Pull request by chunyang-wen**
## Proposed changes

For some of the activations, we define them using a decorator of a class. Like ReLU:

```python
@_make_activation_module(relu)
class ReLU(Module):
    r"""Applies the Rectified Linear Unit.
        Simply ``mx.maximum(x, 0)``.

    See :func:`relu`, for the functional equivalent.
    """
```

When we use `ReLU`:

```python
import mlx.core as mx
from mlx import nn
a = mx.array(-1)
b = nn.ReLU()(a)
print(b)
```
pyright will report a warning complaining that it is not callable.

This PR adds a hint on the module.

## Reference

- https://peps.python.org/pep-0526/#class-and-instance-variable-annotations

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by awni** [comment]
This not the case for me:

```
>>> a = mx.array(-1)
>>> b = nn.ReLU()(a)
>>> print(b)
array(0, dtype=int32)
```

May I ask what version of Python are you using? 
What version of MLX?

**Comment by chunyang-wen** [comment]
I am using vim + coc-pyright. When in the editor, pyright reports a warning about the callable stuff.

image

**Comment by awni** [comment]
I see! What about other activations with the decorator? Should they also have this

**Comment by chunyang-wen** [comment]
> I see! What about other activations with the decorator? Should they also have this

The other activations who define `__call__` themselves are callable and can be identified by mypy.

**Comment by dc-dc-dc** [comment]
Is there a case where a module doesn't return a single array?

If not, can you do `Callable[..., mx.array]` so that the return type hint is there as well?

**Comment by awni** [comment]
I don't think we are prepared to fix the output of `nn.Module` to a single array, so let's merge this as is

**Review by awni — APPROVED** [review]

**Pull request merged**
