### PR TITLE
added mlp notebook example

### PR DESCRIPTION
**Pull request by hinriksnaer**
## Proposed changes

I noticed that there are no jupyter notebook examples in the project. I decided to port the [MLP example](https://ml-explore.github.io/mlx/build/html/python/nn/module.html#mlx.nn.Module) into a simple jupyter notebook that can be run by any new user to get a sense of how mlx works. 

Feel free to make any suggestions for modifications if you like the idea. I am currently not sure if any modifications to the documentation are required.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by angeloskath** [comment]
Thanks for the contribution @hinriksnaer!

Personally I don't think this particular example adds much compared to the one in the docs https://ml-explore.github.io/mlx/build/html/examples/mlp.html or the script itself https://github.com/ml-explore/mlx-examples/tree/main/mnist . Maybe people feel differently @jagrit06 @awni ?

I think it may make more sense with a visual example like the normalizing flow one. However, given that this would also just duplicate an example, I don't know...

**Comment by hinriksnaer** [comment]
I appreciate the feedback @angeloskath!

This is definitely a matter of preference so I understand if this does not fit within the current scope. Personally, when looking into new frameworks, I really appreciate being able to jumpy straight into a notebook and get a feel for the step-by-step process in a hands on manner.  

If you have any suggestions for alternative examples that may contribute more value, feel free to suggest them.

**Comment by awni** [comment]
I can see how for notebook users having a quick way to get started with MLX might be useful, but it's also pretty easy to copy and paste something into a notebook right? Is there something we could do to make the example easier in that respect? MLX isn't really meant to run in colab so it would have to be local, and we couldn't really have like an `open in colab` button.

On the downside more surface area = more maintenance burden for us if we change anything. 

I would defer on adding this until we have a better strategy and sense of how useful it is. One way to get started is for you to make a repo and add some notebooks there. I would gladly point to people to it. Wdyt?

**Comment by Stealeristaken** [comment]
> I can see how for notebook users having a quick way to get started with MLX might be useful, but it's also pretty easy to copy and paste something into a notebook right? Is there something we could do to make the example easier in that respect? MLX isn't really meant to run in colab so it would have to be local, and we couldn't really have like an `open in colab` button.
> 
> On the downside more surface area = more maintenance burden for us if we change anything.
> 
> I would defer on adding this until we have a better strategy and sense of how useful it is. One way to get started is for you to make a repo and add some notebooks there. I would gladly point to people to it. Wdyt?

I tried to create some notebooks with MLX, but it didn't go well. I can't remember the exact errors I faced, but even after creating an MLX array, the notebook kept returning an exception. On the other hand, I believe it would be beneficial to include notebook examples in MLX. I see many ML engineers or data scientists using silicon chips and encountering errors when they try to use traditional libraries.

**Comment by awni** [comment]
@Stealeristaken sounds like you might have some issues with either your Jupyter setup or your MLX setup. The two are pretty independent so if they are both working they should work together. I have no problem doing MLX stuff in a notebook.

Feel free to file an issue if you would like any assistance debugging. But we'll need more information on the issues you were facing..

**Pull request closed without merging**
