### PR TITLE
Change the variance computation

### PR DESCRIPTION
**Pull request by angeloskath**
Changes the computation of variance to a faster one (but slightly less numerically stable). Not sure if we want to merge this but the performance benefit for large reductions is quite big.

### CODE REVIEW

**Comment by awni** [comment]
What do you think about waiting for multi-output primitives and doing a primitive for this instead?

**Comment by angeloskath** [comment]
I think it may be worth doing a primitive but no reason for a multi output one imho.

Computing the mean and passing it as an argument to the variance primitive makes a lot of sense I think.

**Comment by awni** [comment]
Should we close this PR? I don't think we intend to merge it right?

**Comment by angeloskath** [comment]
We can close it but what do we intend to do? Shall we do a primitive? And if yes why? Are we thinking of not merging due to possible numerical instability?

**Review by awni — APPROVED** [review]
My apologies if you were waiting for a review on this. I actually just assumed we didn't plan to merge it because it's a month old 😅 

- If the purpose is just speed, compile would solve that as it's all pretty fuse-able?
- Numerically it does look worse...the uncentered square may cause problems for lower precision. But it doesn't look that bad so I would also just say we can merge it as is and fix it to handle numerics if it becomes an issue.

I'll leave it up to you, I don't feel to strongly about it either way.

**Pull request merged**
