### PR TITLE
Build Docs: Custom Metal Kernels

### PR DESCRIPTION
**Pull request by cdreetz**
## Proposed changes

The site showed an old version of the docs compared to what the rst files showed. Just rebuilt and look like its fixed locally. No code updates, just pushing the build.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [ ] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by angeloskath** [comment]
@cdreetz we appreciate that and we 'll rebuild and upload asap but I don't think there is any way we can actually review 800k lines diff. Would it be ok if we closed this and rebased on on our own and pushed in an hour or so?

**Comment by awni** [comment]
👍  I'll push the updated docs rn. Sorry for the delay.

**Comment by awni** [comment]
FYI this is done.

**Comment by cdreetz** [comment]
@angeloskath yes sorry i didnt realize it included all that other stuff.

@awni thank you awni!

**Pull request closed without merging**
