### PR TITLE
feat: Add numpy constants

### PR DESCRIPTION
**Pull request by AvikantSrivastava**
## Proposed changes

In order to closely mirror numpy offering, mlx should support the constants that numpy offers

mlx did not have support for [numpy constants](https://numpy.org/doc/stable/reference/constants.html#numpy.e) like `pi`, `nan`, `inf` 
GitHub Issue: https://github.com/ml-explore/mlx/issues/365

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by AvikantSrivastava** [comment]
@awni can you take a look?

**Review by awni — CHANGES_REQUESTED** [review]
Nice and simple, this is great!

Could you add a test that checks newaxis works for reshaping arrays? Then we should be good to go.

**Comment by AvikantSrivastava** [comment]
> Nice and simple, this is great!
> 
> Could you add a test that checks newaxis works for reshaping arrays? Then we should be good to go.

done!
can you check?

**Review by awni — APPROVED** [review]
🚀

**Comment by awni** [comment]
Closes #365

**Pull request merged**
