### PR TITLE
`conv_transpose_2d` support

### LINKED ISSUE #269: [Feature Request] ConvTranspose2D
PyTorch Navie Implementation: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/NaiveConvolutionTranspose2d.cpp
PyTorch Navie Cuda Implementation: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/NaiveConvolutionTranspose2d.cu
I guess so this is the metal implementation of Conv Tranpose in PyTorch:
https://github.com/pytorch/pytorch/blob/015bd0e0a189f929e469c6bc75fe1541c18a014d/aten/src/ATen/native/mps/operations/Convolution.mm#L709

### PR DESCRIPTION
**Pull request by ManishAradwad**
## Proposed changes

Please include a description of the problem or feature this PR is addressing. If there is a corresponding issue, include the issue 

closes #269 .

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by ManishAradwad** [comment]
[`tinygrad`](https://github.com/tinygrad/tinygrad/blob/ca66be6a70045f0646214b304da10a6cd1eacb3f/tinygrad/tensor.py#L630) modifies the input to perform trans_conv using conv2d function directly. I thought implementing the ops for transpose separately is more efficient since it involves one step less compared to tinygrad approach( and also tinygrad loves to keep their codebase smaller :) ). Would love to hear thoughts on this. If tinygrad approach is better then I'll do those changes. 

I'm not entirely sure i have implemented `pt_conv_transpose_no_checks` / `pt_conv_transpose_all_checks` properly. Please verify once. 

Also I'll add the tests subsequently.

**Comment by dc-dc-dc** [comment]
For the cpu implementation you can do gemm + col2im, this would only work for float but on accelerate you can use bnns matmul


```python
  const auto m = in_h * in_w;
  const auto n = w_h * w_w * w_cout;
  for (auto i = 0; i < in_b; i++) {
    cblas_sgemm(
        CblasRowMajor,
        CblasTrans,
        CblasNoTrans,
        m,
        n,
        w_cin,
        1.0f, // alpha
        in_p + i * in_strides[0],
        m,
        w_p,
        n,
        0.0f, // beta
        col_p,
        n);
    col2im<float>(
        col_p,
        w_cout,
        out_h,
        out_w,
        in_h,
        in_w,
        w_h,
        w_w,
        padding[0],
        padding[1],
        kernel_strides[0],
        kernel_strides[1],
        dilation[0],
        dilation[1],
        out_p + i * out_strides[0]);
```

**Comment by angeloskath** [comment]
@jagrit06 take a look. I don't know how much of that is obsoleted by your new conv implementation.

**Comment by jagrit06** [comment]
Thanks for the contribution @ManishAradwad !
I should have perhaps added a draft PR of my own but I have been working on an update to convs and it should arrive with some specializations for a transpose conv. 

The way I see it, having a generalized Convolution primitive with lhs and rhs dilation options that then dispatches to the appriroate specialized kernel in the backend (similar to how Jax does it) would be useful and also fill the blanks for the transforms and grads. 

With that in mind, I'm going to have to close this PR for now and I will be sure to add Draft PRs in the future to minimize such collisions 

Also @dc-dc-dc that's a great idea for the CPU implementations! Don't mind if I incorporate something to that effect!

**Comment by dc-dc-dc** [comment]
using gemm + col2im beat out torch on cpu in speed when I was testing it out

**Comment by dc-dc-dc** [comment]
I originally started with the torch implementation but had to mess with it a little bit to get it working with the gemm params I set so might not even be considered col2im anymore, here is the code for what I was using
```c++
template <typename T>
void col2im(
    const T* data_p,
    int channels,
    int out_height,
    int out_width,
    int in_height,
    int in_width,
    int kernel_height,
    int kernel_width,
    int padding_height,
    int padding_width,
    int stride_height,
    int stride_width,
    int dilation_height,
    int dilation_width,
    T* out_p) {
  for (auto _out_h = 0; _out_h < in_height; _out_h++) {
    for (auto _out_w = 0; _out_w < in_width; _out_w++) {
      for (auto _ker_h = 0; _ker_h < kernel_height; _ker_h++) {
        auto h_im =
            _out_h * stride_height - padding_height + _ker_h * dilation_height;
        for (auto _ker_w = 0; _ker_w < kernel_width; _ker_w++) {
          auto w_im =
              _out_w * stride_width - padding_width + _ker_w * dilation_width;
          T* _out_p = out_p + (h_im * out_height + w_im) * channels;
          auto data_off = (_out_h * in_height + _out_w) * kernel_height *
                  kernel_width * channels +
              ((_ker_h * kernel_height) + _ker_w);
          const T* _data_p = data_p + data_off;
          if (h_im >= 0 && h_im < out_height && w_im >= 0 && w_im < out_width) {
            for (int c = 0; c < channels; c++) {
              _out_p[c] += _data_p[c * kernel_height * kernel_width];
            }
          }
        }
      }
    }
  }
}
```

**Comment by dc-dc-dc** [comment]
ideally if the channels are together you could squeeze out some more gains by doing some vector like ops on top

**Pull request closed without merging**
