### PR TITLE
Resolves build issues with the extension example 

### PR DESCRIPTION
**Pull request by dc-dc-dc**
## Proposed changes

Updates extension example with new api, and fixes the build issues with json headers missing.

Also added the build example to ci, ideally should run ci test in this pr before committing to make sure its good.
## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by angeloskath** [comment]
This looks good to me. I am not sure we want to build the example extension at every commit, haven't decided yet. @jagrit06  take a look when you time and approve.

**Comment by dc-dc-dc** [comment]
I think having the examples be part of the test suite makes sense as it ensures that they don't get stale, and developers looking to build on them don't end up running into issues due to missing updates.

**Comment by awni** [comment]
I'm ok with adding it to CircleCI for now. Nevertheless, this should still be viewed as an experimental feature, we may break compatibility with it in the future (in favor of alternative extension approaches). It's one reason we don't advertise it much in the docs.

**Review by awni — APPROVED** [review]
@dc-dc-dc would you mind rebasing? The `Axpby::vjp` needs to take a vector of `outputs` as well now otherwise it won't compile.

After that let's plan to merge it. Thanks for fixing the example!

**Comment by dc-dc-dc** [comment]
rebased, but before merging can we do a quick ci run in this pr to resolve any issues with the ci test script if any?

**Comment by awni** [comment]
Yea I think I can push this as a branch to check that

**Comment by awni** [comment]
CI is running on this branch https://github.com/ml-explore/mlx/tree/extension_ci

**Comment by awni** [comment]
@dc-dc-dc indeed the build did not work. Can you view [this file](https://circleci.com/api/v1.1/project/github/ml-explore/mlx/1650/output/105/0?file=true&allocation-id=65a7f2e9f6278a207a486e7a-0-build%2FABCDEFGH) ?

**Comment by dc-dc-dc** [comment]
Yeah, seems like it’s an issue when installing using a virtual env. when installing globally it’s fine, might be that the install location in make doesn’t line up, will look into this

**Comment by dc-dc-dc** [comment]
@awni can you run it again? I suspect it may be installing a version of mlx on pypi(without the fix) and causing the error. I set it to install from my fix branch for now to test

**Comment by awni** [comment]
I will run it, but I see two options to move forward

1. Remove the CI change and put it in a follow up PR (and pin it to a weekly distribution / the next release)
2. Build mlx locally rather than from PyPi

Wdyt?

**Comment by dc-dc-dc** [comment]
Will update the pyproject.toml to point to `mlx-explore/mlx/main` as after the merge it should work. Then after the next release can point it back to pypi with a version requirement.

For now can omit from the CI tests and add it back when the extension api gets in a more defined state, like you mentioned its still experimental so don't want to enforce that its tests pass as it can change.

**Comment by awni** [comment]
Thanks!!

**Pull request merged**
