### PR TITLE
update mx.random.normal calls

### PR DESCRIPTION
**Pull request by LeonEricsson**
## Proposed changes

updated existing mx.random.normal to make use of #638 

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Review by awni — APPROVED** [review]
Looks great, thanks!

**Comment by awni** [comment]
Any reason to keep this a draft?

**Comment by LeonEricsson** [comment]
> Any reason to keep this a draft?

was waiting to see if #638 changed. do you mind taking a look at the [prompt lookup pr](https://github.com/ml-explore/mlx-examples/pull/237) when you've got some time over, its ready for merge

**Review by awni — APPROVED** [review]
👍

**Pull request merged**
