### PR TITLE
Optimizer Implementations 

### PR DESCRIPTION
**Pull request by AndreSlavescu**
## Proposed changes

Please include a description of the problem or feature this PR is addressing. If there is a corresponding issue, include the issue #.

Implementing other optimizers present in torch (excluding SparseAdam)

## Checklist

- [x] ASGD
- [ ] LBFGS

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by AndreSlavescu** [comment]
Hi @awni , I posted an issue regarding this thread here:

https://github.com/ml-explore/mlx/issues/719

**Comment by awni** [comment]
@AndreSlavescu you should for push after rebasing to avoid brining in old changes. Can you fix the diff on this PR?

**Comment by awni** [comment]
Also I think it's fine to do just one optimizer per PR. So after you clean it up we can decide if we want ASGD and I will review if so.

**Comment by awni** [comment]
I'm closing this for now as I don't think we have a real need for it. We can revive/ revisit if that changes.

In the meantime let's use #718 to track / prioritize adding additional optimizers.

**Pull request closed without merging**
