### PR TITLE
feat: add cross_product

### LINKED ISSUE #1244: [Feature] cross product
It would be nice to have a `mx.cross`/`mx.linalg.cross` that works like `np.cross`/`np.linalg.cross`.

### PR DESCRIPTION
**Pull request by NripeshN**
Closes #1244

### CODE REVIEW

**Review by angeloskath — COMMENTED** [review]
Thanks for the addition!

I would start by making sure that the API follows the corresponding numpy API https://numpy.org/devdocs/reference/generated/numpy.linalg.cross.html including the axis argument.

Regarding the implementation, I would look into `split` and `concatenate`.

**Comment by awni** [comment]
@NripeshN are you planning to come back to this?

**Comment by awni** [comment]
@NripeshN are you planning to come back to this PR?

**Comment by NripeshN** [comment]
> @NripeshN are you planning to come back to this PR?

Hi @awni 
Sorry for the delay and late reply, got caught up with few other tasks. I will continue working on this now.

**Review by awni — APPROVED** [review]
Thanks for the addition!

**Pull request merged**
