### PR TITLE
Experiment with medium machines for CI

### PR DESCRIPTION
**Pull request by madrob**
## Proposed changes

Change the runtime class for CI from large to medium. Most of our builds cap out at 6GB usage so this should be ok. Do not merge until proper analysis has been done of the runtime performance.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [ ] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by madrob** [comment]
CircleCI build on large machine takes 7 minutes, while a build on medium machine is slightly longer at 9 minutes. However, the medium machine is significantly cheaper, still giving us some good savings on cost.

**Review by awni — APPROVED** [review]
@madrob any reason this is still in draft? Tests are passing, let's go ahead and merge it?

**Comment by awni** [comment]
@madrob can we close this or are you still investigating?

**Comment by madrob** [comment]
Should have been marked ready a while ago. Please merge!

**Pull request merged**
