### PR TITLE
Better exceptions in case of invalid operations on `mlx.core.array` (#910)

### PR DESCRIPTION
**Pull request by amirhossein-razlighi**
## Proposed changes

This closes issue #910. In case of invalid operations on an `mlx.core.array`, we throw exceptions that are more meaningful. See the examples below:
```
import mlx.core as mx

a = mx.array([1, 2.0, 3])
str_ = "hello"
tpl_ = (1, 2.1, 3)
lst_ = [1, 2.5, 3.25]

a * str_  # ValueError: Cannot perform multiplication on an mlx.core.array and str
a /= tpl_ # ValueError: Cannot perform inplace division on an mlx.core.array and tuple
a // lst_ # ValueError: Cannot perform floor division on an mlx.core.array and list
# and same for other operations like <+ / - / ** / *= / += / -= / etc.>
```

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Comment by amirhossein-razlighi** [comment]
Please note that I made this branch from (this PR)[https://github.com/ml-explore/mlx/pull/920#issue-2212567287] because the function `is_comparable_with_array` was needed here.
Please let me know if there is something needed to change and any suggestions you have.

**Comment by awni** [comment]
I merged #920, you can rebase on main to clean this PR up.

**Comment by amirhossein-razlighi** [comment]
> I merged #920, you can rebase on main to clean this PR up.

Done ✅

**Comment by amirhossein-razlighi** [comment]
@awni 
Can you please review this PR whenever it's possible for you?
THX

**Review by awni — COMMENTED** [review]
Could you change the name `is_comparable_with_array` to `is_convertible_to_array`? 

O/w I think this looks good.. it doesn't seem to add noticeable overhead.

**Comment by amirhossein-razlighi** [comment]
> Could you change the name `is_comparable_with_array` to `is_convertible_to_array`?

Sure, I can do that. But I think it's not a good idea, since if you look into the logic of this function in `utils.h`, it is not actually checking if the arg is __convirtable__ to an array, but it's checking if it's __comparable__ to an array. (for example, for a python list, it returns `False`. But if it was checking for convertibility, it should've returned `True`)

**Comment by awni** [comment]
Ok fair enough.. comparable is also not the best fit since it's more like `is_operable_with_array` but it's ok for now.

**Comment by amirhossein-razlighi** [comment]
> Ok fair enough.. comparable is also not the best fit since it's more like `is_operable_with_array` but it's ok for now.

Sure, great.

**Review by awni — APPROVED** [review]
Thanks for adding this!!

**Pull request merged**
