### PR TITLE
make python array SupportsAbs conform (like numpy)

### PR DESCRIPTION
**Pull request by dastrobu**
## Proposed changes

make python array [SupportsAbs](https://docs.python.org/3/library/typing.html#typing.SupportsAbs) conform (like numpy)

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Review by awni — APPROVED** [review]
Nice! Thanks!

**Comment by awni** [comment]
This broke our tests for some reason, I can take a look when I’m back at keyboard.

**Comment by dastrobu** [comment]
Sorry, I can take a look as well tomorrow.

**Comment by awni** [comment]
That's ok, I fixed it already #627

**Pull request merged**
